spring:
  application:
    name: eureka-client-provider
server:
  port: 2111
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:password@localhost:1111/eureka
security:
  user:
    name: user
    password: password